feat: there are some bug
mentoring-by-tapas/pritam-guha pull request #24
Opened 2021-09-21 05:32 UTC by Guha-Pritam

2021-09-26 14:17 UTC, atapas requested changes

2021-09-26 14:17 UTC, atapas commented on student-marks-board/index.js
> +			createUI(users[0]['standard_1']);
Instead of passing `users[0]['standard_1']`, `pass only users[0]`

2021-09-26 14:17 UTC, atapas commented on student-marks-board/index.js
> +	const mainDiv = document.getElementById('tableDiv');
```js
let obj = {
  'standard_1': [],
  'standard_2': [],
  'standard_3': [],
....
....
}
```

Do 
```js
let keys = obj.keys(); // [standard_1, standard_2, standard_3]

// loop the above array

```

obj[keys[0]]

2021-09-27 05:39 UTC, atapas requested changes

2021-09-27 05:39 UTC, atapas commented on student-marks-board/index.js
> +            li.innerHTML = `<span>${users[j],[i].name}</span><span>${users[i].grade}</span>`;
This is wrong `${users[j],[i].name}` what is this doing?

2021-09-27 05:50 UTC, Guha-Pritam commented
ami purotai change kore push korechi

On Mon, Sep 27, 2021 at 11:10 AM Tapas Adhikary ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In student-marks-board/index.js
> <https://github.com/mentoring-by-tapas/pritam-guha/pull/24#discussion_r716372548>
> :
>
> > +}
> +fetchData();
> +
> +function createUI(users) {
> +	const mainDiv = document.getElementById('tableDiv');
> +
> +	const ul = document.createElement('ul');
> +	mainDiv.appendChild(ul);
> +
> +    let keys = userData.keys('userData');
> +
> +    for(let j = 0; j <= keys - 1; j++) {
> +        for (let i = 0; i <= users.length - 1; i++) {
> +            const li = document.createElement('li');
> +            li.setAttribute('class','userLi');
> +            li.innerHTML = `<span>${users[j],[i].name}</span><span>${users[i].grade}</span>`;
>
> This is wrong ${users[j],[i].name} what is this doing?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mentoring-by-tapas/pritam-guha/pull/24#pullrequestreview-763853291>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ6JU7T4GGCHRAD7UTKCWSDUD77TBANCNFSM5ENRA2PA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-27 07:20 UTC, atapas requested changes

2021-09-27 07:20 UTC, atapas commented on student-marks-board/index.js
> +            li.innerHTML = `<span>${users[i].name}</span><span>${users[i].grade}</span>`;
Wrong again.. Does your `users[i]` has the `name` property? console log users[i] and debug and check..

Hint: You are not using keys.

2021-10-22 12:36 UTC, atapas requested changes

2021-10-22 12:36 UTC, atapas commented on student-marks-board/index.js
> +
what do you want me to review?

2021-10-26 13:25 UTC, atapas requested changes

2021-10-26 13:25 UTC, atapas commented on student-marks-board/index.js
> +			const keys = Object.keys(users);//get the value from users
I am not clear what is `keys`. Please explain.

2021-10-26 13:25 UTC, atapas commented on student-marks-board/index.js
> +	const term = event.target.value;
Add comments.

2021-12-20 14:23 UTC, closed without merging